// AUTO-GENERATED by scripts/js-merge-duplicates-ultra.ts — merged duplicate
// "Tricky JavaScript Scenario #N" questions (Node.js ULTRA-style JS retrofit,
// Phase 0) redirect to their canonical, renamed pages. Spread into
// next.config redirects().
export const jsMergeRedirects = [
  {
    source: "/interview-question/tricky-javascript-scenario-70-strict-mode-this-bindings-binding-rules",
    destination: "/interview-question/how-does-use-strict-change-what-this-refers-to-inside-a-regular-function-called-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-100-strict-mode-this-bindings-binding-rules",
    destination: "/interview-question/how-does-use-strict-change-what-this-refers-to-inside-a-regular-function-called-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-40-strict-mode-this-bindings-binding-rules",
    destination: "/interview-question/how-does-use-strict-change-what-this-refers-to-inside-a-regular-function-called-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-41-object-groupby",
    destination: "/interview-question/how-would-you-use-object-groupby-to-group-an-array-of-orders-by-status-and-how-d",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-71-object-groupby",
    destination: "/interview-question/how-would-you-use-object-groupby-to-group-an-array-of-orders-by-status-and-how-d",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-11-object-groupby",
    destination: "/interview-question/how-would-you-use-object-groupby-to-group-an-array-of-orders-by-status-and-how-d",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-42-map-groupby",
    destination: "/interview-question/when-would-you-reach-for-map-groupby-instead-of-object-groupby-and-what-problem-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-72-map-groupby",
    destination: "/interview-question/when-would-you-reach-for-map-groupby-instead-of-object-groupby-and-what-problem-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-12-map-groupby",
    destination: "/interview-question/when-would-you-reach-for-map-groupby-instead-of-object-groupby-and-what-problem-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-43-array-prototype-tosorted",
    destination: "/interview-question/how-does-array-prototype-tosorted-differ-from-sort-and-why-does-that-matter-when",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-73-array-prototype-tosorted",
    destination: "/interview-question/how-does-array-prototype-tosorted-differ-from-sort-and-why-does-that-matter-when",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-13-array-prototype-tosorted",
    destination: "/interview-question/how-does-array-prototype-tosorted-differ-from-sort-and-why-does-that-matter-when",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-44-array-prototype-toreversed",
    destination: "/interview-question/how-does-array-prototype-toreversed-avoid-the-classic-bug-of-accidentally-mutati",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-74-array-prototype-toreversed",
    destination: "/interview-question/how-does-array-prototype-toreversed-avoid-the-classic-bug-of-accidentally-mutati",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-14-array-prototype-toreversed",
    destination: "/interview-question/how-does-array-prototype-toreversed-avoid-the-classic-bug-of-accidentally-mutati",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-45-array-prototype-tospliced",
    destination: "/interview-question/how-would-you-remove-an-item-from-an-array-immutably-using-tospliced-and-how-doe",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-75-array-prototype-tospliced",
    destination: "/interview-question/how-would-you-remove-an-item-from-an-array-immutably-using-tospliced-and-how-doe",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-15-array-prototype-tospliced",
    destination: "/interview-question/how-would-you-remove-an-item-from-an-array-immutably-using-tospliced-and-how-doe",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-46-array-prototype-with",
    destination: "/interview-question/how-does-array-prototype-with-let-you-replace-one-array-element-immutably-and-wh",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-76-array-prototype-with",
    destination: "/interview-question/how-does-array-prototype-with-let-you-replace-one-array-element-immutably-and-wh",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-16-array-prototype-with",
    destination: "/interview-question/how-does-array-prototype-with-let-you-replace-one-array-element-immutably-and-wh",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-47-reflect-ownkeys",
    destination: "/interview-question/how-would-you-use-reflect-ownkeys-inside-a-proxy-to-correctly-enumerate-both-str",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-77-reflect-ownkeys",
    destination: "/interview-question/how-would-you-use-reflect-ownkeys-inside-a-proxy-to-correctly-enumerate-both-str",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-17-reflect-ownkeys",
    destination: "/interview-question/how-would-you-use-reflect-ownkeys-inside-a-proxy-to-correctly-enumerate-both-str",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-48-proxy-traps-custom-sets",
    destination: "/interview-question/how-would-you-write-a-proxy-set-trap-that-validates-a-value-before-allowing-an-a",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-78-proxy-traps-custom-sets",
    destination: "/interview-question/how-would-you-write-a-proxy-set-trap-that-validates-a-value-before-allowing-an-a",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-18-proxy-traps-custom-sets",
    destination: "/interview-question/how-would-you-write-a-proxy-set-trap-that-validates-a-value-before-allowing-an-a",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-49-proxy-traps-custom-gets",
    destination: "/interview-question/how-would-you-use-a-proxy-get-trap-to-implement-lazy-loaded-or-computed-properti",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-79-proxy-traps-custom-gets",
    destination: "/interview-question/how-would-you-use-a-proxy-get-trap-to-implement-lazy-loaded-or-computed-properti",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-19-proxy-traps-custom-gets",
    destination: "/interview-question/how-would-you-use-a-proxy-get-trap-to-implement-lazy-loaded-or-computed-properti",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-50-symbol-iterator-custom-generator",
    destination: "/interview-question/how-would-you-make-a-custom-class-iterable-with-for-of-by-implementing-symbol-it",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-80-symbol-iterator-custom-generator",
    destination: "/interview-question/how-would-you-make-a-custom-class-iterable-with-for-of-by-implementing-symbol-it",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-20-symbol-iterator-custom-generator",
    destination: "/interview-question/how-would-you-make-a-custom-class-iterable-with-for-of-by-implementing-symbol-it",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-51-symbol-asynciterator-paging-fetches",
    destination: "/interview-question/how-would-you-implement-symbol-asynciterator-on-a-class-to-transparently-page-th",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-81-symbol-asynciterator-paging-fetches",
    destination: "/interview-question/how-would-you-implement-symbol-asynciterator-on-a-class-to-transparently-page-th",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-21-symbol-asynciterator-paging-fetches",
    destination: "/interview-question/how-would-you-implement-symbol-asynciterator-on-a-class-to-transparently-page-th",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-52-weakset-garbage-collection-behavior",
    destination: "/interview-question/why-would-you-choose-a-weakset-over-a-set-to-track-a-group-of-dom-elements-and-w",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-82-weakset-garbage-collection-behavior",
    destination: "/interview-question/why-would-you-choose-a-weakset-over-a-set-to-track-a-group-of-dom-elements-and-w",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-22-weakset-garbage-collection-behavior",
    destination: "/interview-question/why-would-you-choose-a-weakset-over-a-set-to-track-a-group-of-dom-elements-and-w",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-53-deepclone-with-cycles-detection",
    destination: "/interview-question/how-would-you-write-a-deep-clone-function-that-correctly-handles-a-self-referenc",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-83-deepclone-with-cycles-detection",
    destination: "/interview-question/how-would-you-write-a-deep-clone-function-that-correctly-handles-a-self-referenc",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-23-deepclone-with-cycles-detection",
    destination: "/interview-question/how-would-you-write-a-deep-clone-function-that-correctly-handles-a-self-referenc",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-54-function-currying-with-placeholder-inputs",
    destination: "/interview-question/how-would-you-implement-a-curry-function-that-supports-partial-application-with-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-84-function-currying-with-placeholder-inputs",
    destination: "/interview-question/how-would-you-implement-a-curry-function-that-supports-partial-application-with-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-24-function-currying-with-placeholder-inputs",
    destination: "/interview-question/how-would-you-implement-a-curry-function-that-supports-partial-application-with-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-55-custom-debounce-with-cancel-method",
    destination: "/interview-question/how-would-you-implement-a-debounce-utility-that-also-exposes-a-cancel-method-to-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-85-custom-debounce-with-cancel-method",
    destination: "/interview-question/how-would-you-implement-a-debounce-utility-that-also-exposes-a-cancel-method-to-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-25-custom-debounce-with-cancel-method",
    destination: "/interview-question/how-would-you-implement-a-debounce-utility-that-also-exposes-a-cancel-method-to-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-56-custom-throttle-with-leading-flags",
    destination: "/interview-question/how-would-you-implement-a-throttle-function-with-configurable-leading-and-traili",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-86-custom-throttle-with-leading-flags",
    destination: "/interview-question/how-would-you-implement-a-throttle-function-with-configurable-leading-and-traili",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-26-custom-throttle-with-leading-flags",
    destination: "/interview-question/how-would-you-implement-a-throttle-function-with-configurable-leading-and-traili",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-57-array-element-kinds-optimization",
    destination: "/interview-question/why-can-pushing-a-single-non-numeric-value-into-a-large-numeric-array-tank-its-p",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-87-array-element-kinds-optimization",
    destination: "/interview-question/why-can-pushing-a-single-non-numeric-value-into-a-large-numeric-array-tank-its-p",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-27-array-element-kinds-optimization",
    destination: "/interview-question/why-can-pushing-a-single-non-numeric-value-into-a-large-numeric-array-tank-its-p",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-58-sharedarraybuffer-thread-isolation",
    destination: "/interview-question/how-does-sharedarraybuffer-let-two-web-workers-share-memory-directly-and-what-ra",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-88-sharedarraybuffer-thread-isolation",
    destination: "/interview-question/how-does-sharedarraybuffer-let-two-web-workers-share-memory-directly-and-what-ra",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-28-sharedarraybuffer-thread-isolation",
    destination: "/interview-question/how-does-sharedarraybuffer-let-two-web-workers-share-memory-directly-and-what-ra",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-59-postmessage-transferable-streams",
    destination: "/interview-question/how-would-you-transfer-a-large-arraybuffer-between-a-worker-and-the-main-thread-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-89-postmessage-transferable-streams",
    destination: "/interview-question/how-would-you-transfer-a-large-arraybuffer-between-a-worker-and-the-main-thread-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-29-postmessage-transferable-streams",
    destination: "/interview-question/how-would-you-transfer-a-large-arraybuffer-between-a-worker-and-the-main-thread-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-60-broadcastchannel-multi-tab-updates",
    destination: "/interview-question/how-would-you-use-the-broadcastchannel-api-to-sync-application-state-across-mult",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-90-broadcastchannel-multi-tab-updates",
    destination: "/interview-question/how-would-you-use-the-broadcastchannel-api-to-sync-application-state-across-mult",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-30-broadcastchannel-multi-tab-updates",
    destination: "/interview-question/how-would-you-use-the-broadcastchannel-api-to-sync-application-state-across-mult",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-61-history-api-route-state-handling",
    destination: "/interview-question/how-would-you-use-the-history-api-s-pushstate-and-the-popstate-event-to-build-cl",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-91-history-api-route-state-handling",
    destination: "/interview-question/how-would-you-use-the-history-api-s-pushstate-and-the-popstate-event-to-build-cl",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-31-history-api-route-state-handling",
    destination: "/interview-question/how-would-you-use-the-history-api-s-pushstate-and-the-popstate-event-to-build-cl",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-62-dom-layout-thrashing-remedies",
    destination: "/interview-question/what-causes-layout-thrashing-when-you-read-and-write-dom-properties-in-a-loop-an",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-92-dom-layout-thrashing-remedies",
    destination: "/interview-question/what-causes-layout-thrashing-when-you-read-and-write-dom-properties-in-a-loop-an",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-32-dom-layout-thrashing-remedies",
    destination: "/interview-question/what-causes-layout-thrashing-when-you-read-and-write-dom-properties-in-a-loop-an",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-63-passive-event-listener-scroll-enhancements",
    destination: "/interview-question/why-would-you-add-passive-true-to-a-scroll-or-touchstart-listener-and-what-probl",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-93-passive-event-listener-scroll-enhancements",
    destination: "/interview-question/why-would-you-add-passive-true-to-a-scroll-or-touchstart-listener-and-what-probl",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-33-passive-event-listener-scroll-enhancements",
    destination: "/interview-question/why-would-you-add-passive-true-to-a-scroll-or-touchstart-listener-and-what-probl",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-64-navigator-sendbeacon-final-telemetry",
    destination: "/interview-question/why-is-navigator-sendbeacon-the-right-tool-for-sending-analytics-data-when-a-use",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-94-navigator-sendbeacon-final-telemetry",
    destination: "/interview-question/why-is-navigator-sendbeacon-the-right-tool-for-sending-analytics-data-when-a-use",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-34-navigator-sendbeacon-final-telemetry",
    destination: "/interview-question/why-is-navigator-sendbeacon-the-right-tool-for-sending-analytics-data-when-a-use",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-65-high-resolution-time-api-precision",
    destination: "/interview-question/why-would-you-use-performance-now-instead-of-date-now-to-measure-how-long-a-func",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-95-high-resolution-time-api-precision",
    destination: "/interview-question/why-would-you-use-performance-now-instead-of-date-now-to-measure-how-long-a-func",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-35-high-resolution-time-api-precision",
    destination: "/interview-question/why-would-you-use-performance-now-instead-of-date-now-to-measure-how-long-a-func",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-66-page-visibility-api-interval-freezing",
    destination: "/interview-question/how-would-you-use-the-page-visibility-api-to-pause-a-setinterval-based-poller-wh",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-96-page-visibility-api-interval-freezing",
    destination: "/interview-question/how-would-you-use-the-page-visibility-api-to-pause-a-setinterval-based-poller-wh",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-36-page-visibility-api-interval-freezing",
    destination: "/interview-question/how-would-you-use-the-page-visibility-api-to-pause-a-setinterval-based-poller-wh",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-67-intersectionobserver-lazy-loaded-content",
    destination: "/interview-question/how-would-you-use-intersectionobserver-to-lazy-load-images-only-as-they-scroll-i",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-97-intersectionobserver-lazy-loaded-content",
    destination: "/interview-question/how-would-you-use-intersectionobserver-to-lazy-load-images-only-as-they-scroll-i",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-37-intersectionobserver-lazy-loaded-content",
    destination: "/interview-question/how-would-you-use-intersectionobserver-to-lazy-load-images-only-as-they-scroll-i",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-68-resizeobserver-sizing-alterations-tracking",
    destination: "/interview-question/how-would-you-use-resizeobserver-to-react-to-an-element-s-size-changing-without-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-98-resizeobserver-sizing-alterations-tracking",
    destination: "/interview-question/how-would-you-use-resizeobserver-to-react-to-an-element-s-size-changing-without-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-38-resizeobserver-sizing-alterations-tracking",
    destination: "/interview-question/how-would-you-use-resizeobserver-to-react-to-an-element-s-size-changing-without-",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-69-mutationobserver-tree-monitoring",
    destination: "/interview-question/how-would-you-use-mutationobserver-to-detect-when-a-third-party-script-injects-n",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-99-mutationobserver-tree-monitoring",
    destination: "/interview-question/how-would-you-use-mutationobserver-to-detect-when-a-third-party-script-injects-n",
    permanent: true,
  },
  {
    source: "/interview-question/tricky-javascript-scenario-39-mutationobserver-tree-monitoring",
    destination: "/interview-question/how-would-you-use-mutationobserver-to-detect-when-a-third-party-script-injects-n",
    permanent: true,
  },
];
