/**
 * Self-hosted Monaco loader configuration.
 *
 * @monaco-editor/react fetches the editor from jsdelivr by default, so every
 * playground surface breaks when that CDN hiccups (observed on Mobile
 * Safari). This points the shared loader singleton at our own
 * `public/monaco/vs` build (pinned to monaco-editor@0.55.1 — the exact
 * version the loader expects — and regenerated by `postinstall`).
 *
 * Import this module from every file that renders `@monaco-editor/react`'s
 * Editor. Module scope runs before the first `loader.init()`, so the config
 * always wins regardless of mount order. Workers keep working: `vs/`
 * ships them and the AMD loader resolves them same-origin.
 */
import { loader } from "@monaco-editor/react";

loader.config({ paths: { vs: "/monaco/vs" } });

export { loader };
