// AUTO-GENERATED by scripts/next-merge-duplicates.ts — merged duplicate Next.js
// questions redirect to their canonical pages. Spread into next.config redirects().
export const nextMergeRedirects = [
  {
    "from": "/interview-question/how-do-server-and-client-components-compose-in-next-js",
    "to": "/interview-question/what-is-the-difference-between-server-components-and-client-components-in-next-j"
  },
  {
    "from": "/interview-question/what-are-layouts-and-nested-layouts-in-the-next-js-app-router",
    "to": "/interview-question/what-is-the-difference-between-layout-js-and-template-js-in-next-js"
  },
  {
    "from": "/interview-question/parallel-routes-slot-how-do-you-build-a-dashboard-with-independent-slots",
    "to": "/interview-question/what-are-parallel-routes-slot-in-next-js-and-when-would-you-use-them"
  },
  {
    "from": "/interview-question/intercepting-routes-how-do-you-build-an-instagram-style-modal",
    "to": "/interview-question/what-are-intercepting-routes-in-next-js-and-what-are-they-used-for"
  },
  {
    "from": "/interview-question/what-is-streaming-ssr-with-suspense-in-next-js",
    "to": "/interview-question/what-is-loading-js-in-next-js-and-how-does-suspense-streaming-work"
  },
  {
    "from": "/interview-question/how-do-you-handle-loading-and-error-states-for-data-fetching-in-next-js",
    "to": "/interview-question/what-is-loading-js-in-next-js-and-how-does-suspense-streaming-work"
  },
  {
    "from": "/interview-question/partial-prerendering-ppr-how-do-you-enable-it-incrementally",
    "to": "/interview-question/what-is-partial-prerendering-ppr-in-next-js"
  },
  {
    "from": "/interview-question/how-does-next-js-decide-between-static-and-dynamic-rendering-at-build-time",
    "to": "/interview-question/what-is-the-difference-between-static-and-dynamic-rendering-in-the-next-js-app-r"
  },
  {
    "from": "/interview-question/what-is-the-data-cache-in-next-js-and-how-do-you-opt-out-of-it",
    "to": "/interview-question/how-does-fetch-caching-work-in-the-next-js-app-router-force-cache-no-store-reval"
  },
  {
    "from": "/interview-question/revalidatetag-vs-revalidatepath-when-to-use-which",
    "to": "/interview-question/what-is-on-demand-revalidation-in-next-js-revalidatepath-revalidatetag"
  },
  {
    "from": "/interview-question/how-do-you-revalidate-data-after-a-mutation-in-next-js",
    "to": "/interview-question/what-is-on-demand-revalidation-in-next-js-revalidatepath-revalidatetag"
  },
  {
    "from": "/interview-question/caching-defaults-in-next-15-what-is-no-longer-cached-by-default",
    "to": "/interview-question/what-changed-about-caching-defaults-in-next-js-15"
  },
  {
    "from": "/interview-question/how-do-you-read-request-data-and-return-responses-in-a-next-js-route-handler",
    "to": "/interview-question/what-are-route-handlers-in-next-js-and-how-do-they-differ-from-pages-api-routes"
  },
  {
    "from": "/interview-question/next-font-how-does-it-eliminate-layout-shift-and-external-requests",
    "to": "/interview-question/how-does-next-font-work-and-why-does-it-improve-performance"
  },
  {
    "from": "/interview-question/what-is-the-difference-between-build-time-and-runtime-environment-variables-in-n",
    "to": "/interview-question/how-do-environment-variables-work-in-next-js-the-next-public-prefix"
  },
  {
    "from": "/interview-question/turbopack-why-is-it-10x-faster-than-webpack-in-next-js-15",
    "to": "/interview-question/what-is-turbopack-in-next-js-and-how-does-it-compare-to-webpack"
  },
  {
    "from": "/interview-question/migrating-webpack-config-to-turbopack-what-breaks",
    "to": "/interview-question/what-is-turbopack-in-next-js-and-how-does-it-compare-to-webpack"
  },
  {
    "from": "/interview-question/how-do-you-run-turbopack-locally-next-dev-turbo-vs-default",
    "to": "/interview-question/what-is-turbopack-in-next-js-and-how-does-it-compare-to-webpack"
  },
  {
    "from": "/interview-question/instrumentation-ts-what-changed-for-observability-in-next-15",
    "to": "/interview-question/how-do-you-handle-instrumentation-and-observability-in-next-js-instrumentation-t"
  },
  {
    "from": "/interview-question/observability-with-opentelemetry-in-next-15-how-is-otel-wired",
    "to": "/interview-question/how-do-you-handle-instrumentation-and-observability-in-next-js-instrumentation-t"
  },
  {
    "from": "/interview-question/what-does-use-cache-unlock-in-next-js-15",
    "to": "/interview-question/what-are-cache-components-in-next-js-16-and-how-does-the-use-cache-directive-wor"
  },
  {
    "from": "/interview-question/middleware-in-next-15-what-breaks-from-the-14-upgrade",
    "to": "/interview-question/what-is-proxy-ts-in-next-js-16-and-how-do-you-migrate-from-middleware-ts"
  },
  {
    "from": "/interview-question/what-is-prefetching-in-next-js-and-how-does-next-link-prefetch-routes",
    "to": "/interview-question/how-does-prefetching-and-navigation-caching-work-in-next-js-16"
  },
  {
    "from": "/interview-question/next-config-reactcompiler-should-you-enable-the-react-compiler",
    "to": "/interview-question/how-do-you-enable-and-evaluate-the-react-compiler-in-next-js-16"
  }
].map((r) => ({
  source: r.from,
  destination: r.to,
  permanent: true,
}));
