// AUTO-GENERATED by scripts/node-merge-duplicates.ts — merged duplicate Node.js
// questions redirect to their canonical pages. Spread into next.config redirects().
export const nodeMergeRedirects = [
  {
    "from": "/interview-question/how-does-node-js-handle-multi-threading-behind-the-scenes-if-javascript-is-singl",
    "to": "/interview-question/how-do-you-achieve-concurrency-in-node-js-since-it-s-single-threaded"
  },
  {
    "from": "/interview-question/what-is-the-purpose-of-the-cluster-module-and-how-does-it-utilize-multi-core-cpu",
    "to": "/interview-question/explain-how-clustering-works-in-node-js"
  },
  {
    "from": "/interview-question/what-is-the-difference-between-spawn-and-exec-in-node-js",
    "to": "/interview-question/explain-the-differences-between-fork-spawn-and-exec-in-the-child-process-module"
  },
  {
    "from": "/interview-question/what-is-npm-and-what-are-its-core-functionalities",
    "to": "/interview-question/explain-the-purpose-of-package-json-and-npm"
  },
  {
    "from": "/interview-question/what-is-the-difference-between-string-concatenation-and-path-join-path-resolve",
    "to": "/interview-question/what-is-the-role-of-the-path-module-and-why-is-it-preferred-over-manual-string-c"
  },
  {
    "from": "/interview-question/explain-the-difference-between-require-and-import-in-node-js",
    "to": "/interview-question/describe-the-node-js-module-system-what-are-commonjs-and-es-modules"
  },
  {
    "from": "/interview-question/what-are-unhandledrejections-and-how-do-they-differ-from-uncaughtexceptions",
    "to": "/interview-question/how-do-you-handle-uncaught-exceptions-and-unhandled-promise-rejections-in-node-j"
  }
].map((r) => ({
  source: r.from,
  destination: r.to,
  permanent: true,
}));
