// AUTO-GENERATED by scripts/react-merge-duplicates.ts — merged duplicate React
// questions redirect to their canonical pages. Spread into next.config redirects().
export const reactMergeRedirects = [
  {
    "from": "/interview-question/what-is-the-significance-of-the-key-prop-when-rendering-lists-in-react",
    "to": "/interview-question/what-is-the-purpose-of-the-key-prop-when-rendering-lists-in-react"
  },
  {
    "from": "/interview-question/what-are-keys-in-react-lists",
    "to": "/interview-question/what-is-the-purpose-of-the-key-prop-when-rendering-lists-in-react"
  },
  {
    "from": "/interview-question/what-is-the-purpose-of-key-prop-when-rendering-lists-in-react",
    "to": "/interview-question/what-is-the-purpose-of-the-key-prop-when-rendering-lists-in-react"
  },
  {
    "from": "/interview-question/what-is-the-role-of-a-key-prop-when-rendering-lists-in-react",
    "to": "/interview-question/what-is-the-purpose-of-the-key-prop-when-rendering-lists-in-react"
  },
  {
    "from": "/interview-question/explain-the-concept-of-prop-drilling-and-how-can-it-be-avoided",
    "to": "/interview-question/what-is-prop-drilling-and-how-can-it-be-avoided"
  },
  {
    "from": "/interview-question/explain-prop-drilling-and-how-to-mitigate-it",
    "to": "/interview-question/what-is-prop-drilling-and-how-can-it-be-avoided"
  },
  {
    "from": "/interview-question/explain-the-concept-of-prop-drilling-and-how-to-mitigate-it",
    "to": "/interview-question/what-is-prop-drilling-and-how-can-it-be-avoided"
  },
  {
    "from": "/interview-question/differentiate-between-usestate-and-usereducer-hooks",
    "to": "/interview-question/what-is-the-difference-between-usestate-and-usereducer"
  },
  {
    "from": "/interview-question/explain-the-difference-between-usestate-and-usereducer",
    "to": "/interview-question/what-is-the-difference-between-usestate-and-usereducer"
  },
  {
    "from": "/interview-question/react-virtual-dom-explained",
    "to": "/interview-question/what-is-the-virtual-dom-in-react"
  },
  {
    "from": "/interview-question/explain-the-virtual-dom-in-react",
    "to": "/interview-question/what-is-the-virtual-dom-in-react"
  },
  {
    "from": "/interview-question/what-is-the-difference-between-a-controlled-and-an-uncontrolled-component",
    "to": "/interview-question/what-is-the-difference-between-controlled-and-uncontrolled-components"
  },
  {
    "from": "/interview-question/differentiate-between-controlled-and-uncontrolled-components",
    "to": "/interview-question/what-is-the-difference-between-controlled-and-uncontrolled-components"
  },
  {
    "from": "/interview-question/explain-the-concept-of-uncontrolled-components",
    "to": "/interview-question/what-is-the-difference-between-controlled-and-uncontrolled-components"
  },
  {
    "from": "/interview-question/explain-the-concept-of-immutability-in-react-state-management",
    "to": "/interview-question/why-must-react-state-updates-be-immutable"
  },
  {
    "from": "/interview-question/why-should-we-not-update-state-directly",
    "to": "/interview-question/why-must-react-state-updates-be-immutable"
  },
  {
    "from": "/interview-question/what-is-the-concept-of-immutability-in-react-state-management",
    "to": "/interview-question/why-must-react-state-updates-be-immutable"
  },
  {
    "from": "/interview-question/explain-how-react-handles-events",
    "to": "/interview-question/how-does-react-handle-events"
  },
  {
    "from": "/interview-question/explain-how-event-handling-works-in-react",
    "to": "/interview-question/how-does-react-handle-events"
  },
  {
    "from": "/interview-question/what-is-the-purpose-of-react-memo",
    "to": "/interview-question/what-is-react-memo-and-when-would-you-use-it"
  },
  {
    "from": "/interview-question/react-usememo",
    "to": "/interview-question/what-is-the-difference-between-usememo-and-usecallback"
  },
  {
    "from": "/interview-question/when-would-you-use-usememo-or-usecallback",
    "to": "/interview-question/what-is-the-difference-between-usememo-and-usecallback"
  },
  {
    "from": "/interview-question/explain-the-concept-of-lifting-state-up",
    "to": "/interview-question/explain-the-concept-of-lifting-state-up-in-react"
  },
  {
    "from": "/interview-question/describe-the-concept-of-unidirectional-data-flow-in-react",
    "to": "/interview-question/explain-the-concept-of-unidirectional-data-flow-in-react"
  },
  {
    "from": "/interview-question/what-are-react-developer-tools",
    "to": "/interview-question/what-are-react-developer-tools-and-how-do-you-use-them"
  },
  {
    "from": "/interview-question/what-are-custom-hooks-and-why-would-you-create-one",
    "to": "/interview-question/what-are-react-custom-hooks-and-when-should-you-use-them"
  },
  {
    "from": "/interview-question/how-do-you-handle-global-state-management-in-a-large-react-application",
    "to": "/interview-question/how-do-you-manage-global-state-in-a-large-react-application"
  },
  {
    "from": "/interview-question/explain-how-to-debug-react-applications",
    "to": "/interview-question/how-do-you-debug-react-applications"
  },
  {
    "from": "/interview-question/explain-the-concept-of-higher-order-components-hocs-in-react",
    "to": "/interview-question/what-are-higher-order-components-hocs-in-react"
  },
  {
    "from": "/interview-question/what-is-the-context-api-in-react",
    "to": "/interview-question/what-is-the-context-api-in-react-and-when-would-you-use-it"
  },
  {
    "from": "/interview-question/what-is-the-purpose-of-the-deps-array-in-useeffect",
    "to": "/interview-question/what-is-the-purpose-of-the-deps-array-in-useeffect-and-usecallback"
  },
  {
    "from": "/interview-question/what-is-the-significance-of-the-deps-array-in-useeffect",
    "to": "/interview-question/what-is-the-purpose-of-the-deps-array-in-useeffect-and-usecallback"
  },
  {
    "from": "/interview-question/what-is-dependency-array-in-useeffect-and-usecallback",
    "to": "/interview-question/what-is-the-purpose-of-the-deps-array-in-useeffect-and-usecallback"
  },
  {
    "from": "/interview-question/what-is-strict-mode-in-react",
    "to": "/interview-question/what-is-the-purpose-of-react-strictmode"
  },
  {
    "from": "/interview-question/what-are-the-core-principles-behind-react-s-design",
    "to": "/interview-question/what-are-react-s-design-principles"
  },
  {
    "from": "/interview-question/how-do-you-prevent-re-renders-in-functional-components",
    "to": "/interview-question/how-do-you-prevent-unnecessary-re-renders-in-functional-components"
  }
].map((r) => ({
  source: r.from,
  destination: r.to,
  permanent: true,
}));
