import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./tests/setup.ts"],
    globals: true,
    // Playwright specs live under tests/e2e and must not run under vitest. Also exclude worktrees.
    // .react-verify is generated by scripts/verify-react-examples.mts and runs
    // under its own config — it must not join the normal unit-test run.
    exclude: ["**/node_modules/**", "tests/e2e/**", "**/.claude/**", "**/.git/**", ".react-verify/**"],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
