// Types + pure helpers for ChallengeForm that need to be importable from
// both server components (the create/edit page wrappers) and client code
// (the form itself). Pulled out of ChallengeForm.tsx because that file is
// "use client" — server components can't call functions exported from a
// client module.

export type TestCaseInput = {
  id: string;
  name: string;
  input: string;
  expected: string;
  isHidden: boolean;
  weight: number;
};

/** "harness" = multi-language function judge; "unit-js" = legacy Jest;
 *  "frontend" = manual-review UI challenge. */
export type JudgingMode = "harness" | "unit-js" | "frontend";

export type ContractParamInput = { name: string; type: string };

/** A harness test case. `expectedJson` is generated by the Validate step. */
export type HarnessTestInput = {
  id: string;
  name: string;
  /** JSON array of arguments, in declared param order. */
  argsJson: string;
  /** Canonical JSON of the expected return value (filled by Validate). */
  expectedJson: string;
  isHidden: boolean;
  weight: number;
  compare: "exact" | "float" | "unordered";
};

/** Languages selectable for harness challenges. */
export const HARNESS_LANGUAGES = ["python", "javascript", "typescript", "go", "java", "cpp", "rust"] as const;

export type ChallengeStepInput = {
  title: string;
  description: string;
  template: string;
  starterFilesJson: string;
  testFilesJson: string;
  estimatedMinutes: number;
  hint: string;
  videoUrl: string;
  testCases: TestCaseInput[];

  // ── Function-harness authoring (judgingMode === "harness") ──
  judgingMode: JudgingMode;
  functionName: string;
  params: ContractParamInput[];
  returnType: string;
  languages: string[];
  /** { lang: reference code } — author-only. */
  referenceSolutions: Record<string, string>;
  /** { lang: starter stub } — generated by Validate, author-editable. */
  starterCode: Record<string, string>;
  harnessTests: HarnessTestInput[];
};

export type ChallengeFormInput = {
  id?: string;
  slug: string;
  title: string;
  /** Markdown shown on the detail page above the step list. */
  description: string;
  difficulty: "easy" | "medium" | "hard";
  tagsCsv: string;
  category: string;
  published: boolean;
  visibility: "public" | "private";
  /** Staff-pick flag — admin only. Authors can't self-feature. */
  featured: boolean;
  /** Whether the challenge requires a paid premium subscription (admin only) */
  premium: boolean;
  steps: ChallengeStepInput[];
};

export type ChallengeFormSurface = {
  redirectTo: string;
  createEndpoint: string;
  itemEndpoint: string;
  isAdmin: boolean;
};

/** Maps a persisted ChallengeStep row to the form's step input, hydrating the
 *  harness fields from their JSON columns. Pure + server-safe. */
export function stepInputFromDb(s: {
  title: string | null;
  description: string;
  template: string;
  starterFiles: string;
  testFiles: string;
  estimatedMinutes: number;
  hint: string | null;
  videoUrl: string | null;
  testCasesJson: string;
  judgingMode?: string | null;
  functionName?: string | null;
  signatureJson?: string | null;
  languagesJson?: string | null;
  starterCodeJson?: string | null;
  referenceSolutionsJson?: string | null;
  harnessTestsJson?: string | null;
}): ChallengeStepInput {
  const pretty = (raw: string) => {
    try {
      return JSON.stringify(JSON.parse(raw), null, 2);
    } catch {
      return raw;
    }
  };
  const parse = <T,>(raw: string | null | undefined, fallback: T): T => {
    if (!raw) return fallback;
    try {
      return JSON.parse(raw) as T;
    } catch {
      return fallback;
    }
  };
  const sig = parse<{ params?: ContractParamInput[]; returnType?: string }>(s.signatureJson, {});
  return {
    title: s.title ?? "",
    description: s.description,
    template: s.template,
    starterFilesJson: pretty(s.starterFiles),
    testFilesJson: pretty(s.testFiles),
    estimatedMinutes: s.estimatedMinutes,
    hint: s.hint ?? "",
    videoUrl: s.videoUrl ?? "",
    testCases: parse<TestCaseInput[]>(s.testCasesJson, []),
    judgingMode: (s.judgingMode as JudgingMode) ?? "unit-js",
    functionName: s.functionName ?? "solve",
    params: sig.params ?? [{ name: "n", type: "int" }],
    returnType: sig.returnType ?? "int",
    languages: parse<string[]>(s.languagesJson, [...HARNESS_LANGUAGES]),
    referenceSolutions: parse<Record<string, string>>(s.referenceSolutionsJson, {}),
    starterCode: parse<Record<string, string>>(s.starterCodeJson, {}),
    harnessTests: parse<HarnessTestInput[]>(s.harnessTestsJson, []),
  };
}

/** Returns a fresh empty step — used when initialising a new challenge or
 *  when the user clicks "Add another question". Pure, server-safe. */
export function blankStep(): ChallengeStepInput {
  return {
    title: "",
    description: "",
    template: "test-ts",
    starterFilesJson: `{\n  "/index.ts": "export function solve() {}\\n"\n}`,
    testFilesJson: `{\n  "/index.test.ts": "import { solve } from './index';\\n\\ntest('placeholder', () => {\\n  expect(true).toBe(true);\\n});\\n"\n}`,
    estimatedMinutes: 15,
    hint: "",
    videoUrl: "",
    testCases: [],
    // New challenges default to the multi-language harness judge.
    judgingMode: "harness",
    functionName: "solve",
    params: [{ name: "n", type: "int" }],
    returnType: "int",
    languages: [...HARNESS_LANGUAGES],
    referenceSolutions: {},
    starterCode: {},
    harnessTests: [],
  };
}
