/**
 * Next.js ULTRA — batch 01 (upgraded 2026-09-23): what Next.js is, App vs Pages Router, rendering strategies, Server vs Client Components.
 * Regenerated by the build script with Verified sections from the Next.js 16.3.4 lab; replaces the earlier version of this file.
 */
import type { NextAugment } from "./nextjs-augments.types";

const augments: NextAugment[] = [
  // ══════════════════════════════════════════════════════════════════════════
  {
    title: "What is Next.js and what problems does it solve?",
    seoDescription: "Next.js is a React framework adding routing, server rendering, data fetching, caching and bundling. What it solves, with output from a 16.3.4 lab.",
    description: `**Question presented to candidate:**
"Our team builds React single-page apps with Vite. Why would we move to Next.js, and what does it actually add on top of React?"

**What a strong answer should cover:**
- React is a UI library; Next.js is a full-stack framework built on it that decides routing, rendering, data fetching, bundling and deployment.
- It renders on the server (static, ISR, dynamic, streaming, partial prerendering), so pages arrive with content and metadata, which helps SEO and first paint.
- React Server Components are the default, so server-only code and data access do not ship to the browser.
- It includes file-based routing, layouts, Server Actions and Route Handlers for the backend, image and font optimization, Metadata API, and Turbopack.
- The trade-off: a server runtime (or a platform), more concepts to learn (caching, server and client boundaries), and framework conventions.

**Clarifying questions expected:**
- "Is the app mostly behind a login or public and SEO sensitive?" — server rendering matters most for public pages.
- "Where will it run?" — a Node server, a platform, or static hosting changes which features are available.

**Code / implementation expected:** Yes — a minimal App Router app with a server page and a client component.`,
    answer: `**Target Audience:** Frontend engineers preparing for Next.js interviews — assumes basic React and App Router familiarity.
**Difficulty:** Easy

> **How to read this doc:** Each idea is explained in plain language first, then tagged with \`📌 Interview term:\`. Every behaviour claim was checked against the Next.js 16.3.4 docs shipped with the package and, in the **Verified** section, against real output from a build or a running server.

## 1. Why This Even Matters — A Story First

React gives you excellent bricks. Building a house from bricks alone means designing the plumbing, wiring and foundations yourself: a router, a server, data loading, bundling, image handling. Next.js is a building kit that comes with those systems already laid out and connected. You still decide the rooms, but you do not reinvent the pipes for every house.

## 2. The Core Idea

📌 **Interview term: Framework** — a set of conventions and tools that decides the structure of an application, as opposed to a library you call from your own structure.

📌 **Interview term: Server rendering** — producing HTML on the server (at build time or per request) so the browser receives content, not an empty shell.

📌 **Interview term: App Router** — the Next.js router based on the app directory, React Server Components, layouts and streaming; the default since Next.js 13.4.

<svg class="iq-diagram" width="100%" viewBox="0 0 660 268" role="img" aria-label="What Next.js adds on top of React. React alone (SPA), Next.js">
  <defs>
    <marker id="nx01xxc5-arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto">
      <path class="d-arrow" d="M0,0 L7,3 L0,6 Z"/>
    </marker>
  </defs>
  <text class="d-text" x="330" y="24" text-anchor="middle">What Next.js adds on top of React</text>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.1s" dur="0.5s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="48" width="280" height="136" rx="10"/>
    <text class="d-text" x="164" y="78" text-anchor="middle">React alone (SPA)</text>
    <text class="d-sub" x="164" y="106" text-anchor="middle">UI components and state</text>
    <text class="d-sub" x="164" y="128" text-anchor="middle">routing, data, SSR: your choice</text>
    <text class="d-sub" x="164" y="150" text-anchor="middle">HTML arrives empty</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.5s" dur="0.4s" fill="freeze"/>
    <path class="d-edge" d="M 307 116 L 353 116" marker-end="url(#nx01xxc5-arrow)"/>
    <circle class="d-accent" r="5">
      <animateMotion dur="2s" repeatCount="indefinite" path="M 307 116 L 353 116"/>
      <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.12;0.88;1" dur="2s" repeatCount="indefinite"/>
    </circle>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.9s" dur="0.5s" fill="freeze"/>
    <rect class="d-box-accent" x="356" y="48" width="280" height="136" rx="10"/>
    <text class="d-text d-accent" x="496" y="78" text-anchor="middle">Next.js</text>
    <text class="d-sub" x="496" y="106" text-anchor="middle">routing, layouts, data fetching</text>
    <text class="d-sub" x="496" y="128" text-anchor="middle">server rendering and caching</text>
    <text class="d-sub" x="496" y="150" text-anchor="middle">HTML arrives with content</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="1.3s" dur="0.6s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="206" width="612" height="44" rx="10"/>
    <text class="d-sub" x="330" y="233" text-anchor="middle">lab build: one app produced static, SSG, ISR and dynamic routes from ordinary code</text>
  </g>
</svg>

The value is not any single feature but that routing, rendering, data and bundling are designed to work together, with the server doing the first render.

## 3. What it solves

| Problem in a plain React SPA | What Next.js provides |
| :--- | :--- |
| Empty HTML until JavaScript runs (SEO, slow first paint) | Server rendering: static, ISR, dynamic, streaming, PPR |
| Choosing and wiring a router | File-based routing with layouts, loading and error files |
| Data fetching waterfalls in the browser | Async Server Components fetching on the server |
| A separate backend for small mutations | Server Actions and Route Handlers |
| Large JavaScript bundles | Server Components ship no client code; automatic code splitting |
| Image and font performance | next/image and next/font |
| Build tooling | Turbopack, TypeScript support, environment handling |

## 4. When it is not the right tool

A purely client-side tool behind a login, with no SEO needs and a separate API, may be simpler as a Vite SPA. Next.js also brings its own concepts (caching layers, the client boundary) that a team has to learn. For the router choice see [App Router vs Pages Router](/interview-question/what-is-the-difference-between-the-app-router-and-the-pages-router), and for rendering modes [rendering strategies](/interview-question/what-are-the-rendering-strategies-in-next-js-ssr-ssg-isr-csr).

## 5. Verified — One Lab App, Many Rendering Modes (Next.js 16.3.4)

A single lab app built with \`next build\`; each route got its mode from its own code, with no global setting:

\`\`\`
Route (app)             Revalidate  Expire
┌ ○ /
├ ○ /_not-found
├ ○ /about
├ ƒ /blocking
├ ○ /blog
├   /blog/[slug]
│ ├ ● /blog/one
│ ├ ● /blog/two
│ └ ● /blog/three
├ ○ /boundary
├ ƒ /cookies
├ ○ /counter
├ ○ /dashboard
├ ƒ /dashboard/boom
├ ƒ /dashboard/missing
├ ƒ /dashboard/slow
├ ○ /isr                       30s      1y
├ ○ /secret
├ ƒ /serial/bigint
├ ƒ /serial/date
├ ƒ /serial/fn
├ ƒ /serial/handler
├ ƒ /serial/klass
├ ƒ /serial/map
├ ƒ /serial/nested
├ ƒ /serial/promise
└ ƒ /serial/set


○  (Static)   prerendered as static content
●  (SSG)      prerendered as static HTML (uses generateStaticParams)
ƒ  (Dynamic)  server-rendered on demand
\`\`\`

And what those modes mean for the first byte a user receives:

\`\`\`
each route requested twice (first request warms it), second one timed; page work = 1500 ms for the dynamic ones, 1200 ms for the PPR hole
static page (○)              first byte    12 ms   complete    13 ms   served from the prerendered file
ISR page (○ + 30s)           first byte    22 ms   complete    22 ms   prerendered, revalidated in the background
dynamic, no loading.js (ƒ)   first byte  1546 ms   complete  1548 ms   server waits 1500 ms before sending anything
dynamic + loading.js (ƒ)     first byte    24 ms   complete  1533 ms   fallback streams first, then the content
Partial Prerender (◐)        first byte    16 ms   complete  1233 ms   static shell + fallback first, hole streams in
\`\`\`

## 6. Common Pitfalls

- **Treating Next.js as "React plus a router".** Its rendering and caching model decides performance and correctness; learn it.
- **Making everything a Client Component.** It throws away the main benefit (server rendering without shipping code).
- **Assuming it needs Vercel.** It runs on any Node server or container; static export is available with fewer features.
- **Ignoring caching.** Data and pages can be cached at several levels; stale data is a common first surprise.
- **Picking it for an app that does not need a server.** A client-only internal tool may be simpler without it.

## 7. How to Answer in an Interview

<div style="background:#1c140a;border:2px solid #f9a825;border-radius:10px;padding:20px 24px;margin:20px 0;">

<div style="color:#ffca28;font-size:1.15em;font-weight:bold;margin-bottom:16px;">🎤 Quick Revision — read this the morning of the interview</div>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 10px 0;">The 60-Second Answer</div>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">1. The one-line answer:</strong> <span style="color:#f0e2c8;">Next.js is a React framework: it adds routing, server rendering, data fetching, caching, bundling and deployment conventions.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">2. How it works:</strong> <span style="color:#f0e2c8;">It renders on the server, so pages arrive with content and metadata; the lab app mixed static, ISR, dynamic and PPR routes.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">3. Why it matters:</strong> <span style="color:#f0e2c8;">Server Components are the default, so server code and data access never ship to the browser.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">4. The detail to add:</strong> <span style="color:#f0e2c8;">It includes the backend pieces (Server Actions, Route Handlers) and performance tools (next/image, next/font, Turbopack).</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">5. The trap to avoid:</strong> <span style="color:#f0e2c8;">The cost is a server runtime and new concepts to learn, like caching and the client boundary.</span>
</blockquote>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:22px 0 10px 0;border-top:1px solid #4a3a1a;padding-top:16px;">Follow-Up Questions to Expect</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:12px 0 0 0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Is Next.js a backend framework?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">Partly. Server Components, Server Actions and Route Handlers run on the server, which covers many backend needs of a web app; large systems still keep separate services.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">What is the difference between Next.js and Create React App or Vite?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">CRA and Vite build client-side apps; Next.js adds server rendering, routing, data fetching on the server and a production server.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Does Next.js lock you into Vercel?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">No. <code style="background:#332310;color:#ffca28;padding:1px 5px;border-radius:3px;">next start</code>, Docker with standalone output, and static export all work without Vercel; platforms add managed caching and scaling.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">What changed with Next.js 16?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">Turbopack by default, Cache Components with 'use cache', proxy.ts replacing middleware, async request APIs everywhere, and new next/image defaults, among others.</span>
</div>

</div>

## 8. Quick Glossary

| Term | Plain meaning |
| :--- | :--- |
| **Framework** | Conventions and tools that shape the whole app |
| **Server rendering** | HTML produced on the server |
| **App Router** | Router based on the app directory and RSC |
| **Turbopack** | Default bundler in Next.js 16 |

---
**Conclusion:** Next.js turns React from a UI library into a complete web framework: routing, server rendering, data, caching, bundling and a production server designed together. The lab build showed one app producing several rendering modes from ordinary component code. The trade-off is a server runtime and a richer mental model, which pays off most for public, content-heavy or performance-sensitive apps.`,
    examples: [
      {
        label: "A minimal App Router app",
        tech: "tsx",
        runnable: false,
        code: `// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>;
}

// app/page.tsx (Server Component: runs on the server, ships no JavaScript)
import LikeButton from "./LikeButton";
export default async function Home() {
  const posts = await fetch("https://api.example.com/posts", { next: { revalidate: 60 } }).then((r) => r.json());
  return (
    <main>
      {posts.map((p: { id: string; title: string }) => <h2 key={p.id}>{p.title}</h2>)}
      <LikeButton />
    </main>
  );
}

// app/LikeButton.tsx (Client Component: interactive)
"use client";
import { useState } from "react";
export default function LikeButton() {
  const [likes, setLikes] = useState(0);
  return <button onClick={() => setLikes(likes + 1)}>Like ({likes})</button>;
}`,
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  {
    title: "What is the difference between the App Router and the Pages Router?",
    seoDescription: "The App Router uses app/, Server Components, layouts and streaming; the Pages Router uses pages/ and getServerSideProps. Both in one 16.3.4 build.",
    description: `**Question presented to candidate:**
"Next.js has two routers. What is the difference, which one would you choose for a new project, and can they coexist?"

**What a strong answer should cover:**
- Pages Router (\`pages/\`): every file is a route, data via getServerSideProps and getStaticProps, all components are client components that also ship to the browser.
- App Router (\`app/\`): folders are routes and only page files are public; React Server Components by default; nested layouts, loading and error files, streaming, Server Actions.
- The App Router is the recommended choice for new projects; the Pages Router is still supported.
- Both can live in one project, which allows incremental migration; navigation between them is a full page load.
- Pages Router props are serialized into \`__NEXT_DATA__\`; the App Router sends an RSC payload of rendered output.

**Clarifying questions expected:**
- "New project or existing app?" — new projects use the App Router.
- "Which libraries depend on next/router or _app?" — they influence the migration order.

**Code / implementation expected:** Yes — the same page in both routers.`,
    answer: `**Target Audience:** Frontend engineers preparing for Next.js interviews — assumes basic React and App Router familiarity.
**Difficulty:** Medium

> **How to read this doc:** Each idea is explained in plain language first, then tagged with \`📌 Interview term:\`. Every behaviour claim was checked against the Next.js 16.3.4 docs shipped with the package and, in the **Verified** section, against real output from a build or a running server.

## 1. Why This Even Matters — A Story First

The Pages Router is a building where every room has its own front door and each room is decorated from scratch. The App Router is a building with shared corridors (layouts) that stay lit while you walk between rooms, rooms that are partly built in the factory (Server Components), and doors that can show you a waiting area while the room finishes (loading). You can keep both buildings on the same street, but walking from one to the other means going outside.

## 2. The Core Idea

📌 **Interview term: Pages Router** — the original Next.js router based on the pages directory, with data functions like getServerSideProps.

📌 **Interview term: App Router** — the Next.js router based on the app directory, React Server Components, nested layouts and streaming.

📌 **Interview term: Hard navigation** — a full page load; it happens when navigating between the two routers.

<svg class="iq-diagram" width="100%" viewBox="0 0 660 268" role="img" aria-label="Two routers, one project (lab). pages/, app/">
  <defs>
    <marker id="nx021wj5-arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto">
      <path class="d-arrow" d="M0,0 L7,3 L0,6 Z"/>
    </marker>
  </defs>
  <text class="d-text" x="330" y="24" text-anchor="middle">Two routers, one project (lab)</text>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.1s" dur="0.5s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="48" width="280" height="136" rx="10"/>
    <text class="d-text" x="164" y="78" text-anchor="middle">pages/</text>
    <text class="d-sub" x="164" y="106" text-anchor="middle">every file is a route</text>
    <text class="d-sub" x="164" y="128" text-anchor="middle">getServerSideProps, props in HTML</text>
    <text class="d-sub" x="164" y="150" text-anchor="middle">components ship to the browser</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.5s" dur="0.4s" fill="freeze"/>
    <path class="d-edge" d="M 307 116 L 353 116" marker-end="url(#nx021wj5-arrow)"/>
    <circle class="d-accent" r="5">
      <animateMotion dur="2s" repeatCount="indefinite" path="M 307 116 L 353 116"/>
      <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.12;0.88;1" dur="2s" repeatCount="indefinite"/>
    </circle>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.9s" dur="0.5s" fill="freeze"/>
    <rect class="d-box-accent" x="356" y="48" width="280" height="136" rx="10"/>
    <text class="d-text d-accent" x="496" y="78" text-anchor="middle">app/</text>
    <text class="d-sub" x="496" y="106" text-anchor="middle">folders + page files</text>
    <text class="d-sub" x="496" y="128" text-anchor="middle">Server Components by default</text>
    <text class="d-sub" x="496" y="150" text-anchor="middle">layouts, streaming, actions</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="1.3s" dur="0.6s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="206" width="612" height="44" rx="10"/>
    <text class="d-sub" x="330" y="233" text-anchor="middle">crossing from app/ to pages/ was a full document load in the lab; inside app/ it stayed in the page</text>
  </g>
</svg>

The routers differ less in URL mapping than in where code runs and what is sent to the browser.

## 3. Side by side

| | Pages Router | App Router |
| :--- | :--- | :--- |
| Directory | \`pages/\` | \`app/\` |
| Route files | Every file | Only \`page\` and \`route\` files |
| Components | All client (hydrated) | Server by default, \`'use client'\` opt-in |
| Data fetching | getServerSideProps, getStaticProps | async Server Components, fetch caching |
| Layouts | \`_app\` and per-page patterns | Nested \`layout\` files that persist |
| Loading and errors | Manual | \`loading\`, \`error\`, \`not-found\` files |
| Mutations | API routes | Server Actions, Route Handlers |
| Payload | \`__NEXT_DATA__\` props JSON | RSC payload |

## 4. Choosing

Use the App Router for new work; it is where new features land (Cache Components, PPR, Server Actions). Keep existing Pages Router code where migration has no payoff yet, and migrate section by section. See [the migration guide](/interview-question/how-do-you-migrate-from-the-pages-router-to-the-app-router-in-next-js) and [getServerSideProps vs App Router data](/interview-question/what-is-the-difference-between-getserversideprops-getstaticprops-and-app-router-).

## 5. Verified — Both Routers in One App (Next.js 16.3.4)

\`\`\`
GET /legacy-ssr (pages/, getServerSideProps returns { at, secretFromServer })
  __NEXT_DATA__ script: {"props":{"pageProps":{"at":"2026-09-23T06:41:57.146Z","secretFromServer":"only-needed-on-server"},"__N_SSP":true},"page":"/legacy-ssr","query":{},"buildId":"hjHQSMX0f_tcwIn_pnd7H","isFallback":false,"isExperimentalCompile":false,
  contains secretFromServer even though the component never renders it: true
GET /counter (app/, Server Component page with one client Counter)
  __NEXT_DATA__ present: false; RSC payload scripts (self.__next_f.push): 1

build table:
  Route (pages): ƒ /legacy-ssr   ● /legacy-ssg (1m revalidate)   Route (app): ○ /counter
\`\`\`

Navigating between them in a real browser:

\`\`\`
one app with both routers (app/ and pages/), real browser, next start; a marker variable is set on window before navigating
router.push("/nav/b")        App Router -> App Router      same document, window marker kept: true
router.push("/legacy-ssg")   App Router -> Pages Router    full document load, window marker kept: false
\`\`\`

## 6. Common Pitfalls

- **Assuming every file in app/ is a route.** Only page and route files are; helpers can live beside them.
- **Using next/router in app/.** The App Router uses next/navigation.
- **Expecting getServerSideProps in app/.** Fetch in Server Components instead.
- **Mixed routers for tightly linked pages.** Each crossing is a full page load.
- **Returning secrets as page props in pages/.** They end up in __NEXT_DATA__ even when not rendered, as the lab showed.

## 7. How to Answer in an Interview

<div style="background:#1c140a;border:2px solid #f9a825;border-radius:10px;padding:20px 24px;margin:20px 0;">

<div style="color:#ffca28;font-size:1.15em;font-weight:bold;margin-bottom:16px;">🎤 Quick Revision — read this the morning of the interview</div>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 10px 0;">The 60-Second Answer</div>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">1. The one-line answer:</strong> <span style="color:#f0e2c8;">The Pages Router maps every file in pages/ to a route and uses page-level data functions; all components ship to the browser.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">2. How it works:</strong> <span style="color:#f0e2c8;">The App Router uses folders with page files, Server Components by default, nested layouts, streaming and Server Actions.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">3. Why it matters:</strong> <span style="color:#f0e2c8;">In the lab one build listed both, and the Pages page shipped unrendered props in __NEXT_DATA__.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">4. The detail to add:</strong> <span style="color:#f0e2c8;">They coexist for incremental migration, but crossing between them is a full page load.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">5. The trap to avoid:</strong> <span style="color:#f0e2c8;">New projects should use the App Router; migrate old ones section by section.</span>
</blockquote>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:22px 0 10px 0;border-top:1px solid #4a3a1a;padding-top:16px;">Follow-Up Questions to Expect</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:12px 0 0 0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Is the Pages Router deprecated?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">No, it is still supported, but new features target the App Router and it is the recommended default.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Can a layout be shared between the two routers?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">Not directly; each router has its own layout mechanism. Share components, not layouts.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Why is navigation between them a full page load?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">They use different client routers and payload formats, so the browser must load a new document; Link prefetching also does not cross routers.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Which one is faster?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">The App Router usually ships less JavaScript because Server Components are not hydrated, and it streams; actual results depend on the app.</span>
</div>

</div>

## 8. Quick Glossary

| Term | Plain meaning |
| :--- | :--- |
| **Pages Router** | pages/ based router with data functions |
| **App Router** | app/ based router with Server Components |
| **__NEXT_DATA__** | Props JSON in Pages Router HTML |
| **Hard navigation** | Full page load between routers |

---
**Conclusion:** The App Router and the Pages Router map URLs similarly but differ in where code runs and what reaches the browser. The lab ran both in one app: the Pages page shipped its props JSON, the App page an RSC payload, and navigation between them reloaded the page. Use the App Router for new work and migrate the old one gradually.`,
    examples: [
      {
        label: "The same product page in both routers",
        tech: "tsx",
        runnable: false,
        code: `// pages/products/[id].tsx  (Pages Router)
export async function getServerSideProps({ params }: { params: { id: string } }) {
  return { props: { product: await getProduct(params.id) } };
}
export default function Product({ product }: { product: { name: string } }) {
  return <h1>{product.name}</h1>;
}

// app/products/[id]/page.tsx  (App Router)
export default async function Product({ params }: { params: Promise<{ id: string }> }) {
  const product = await getProduct((await params).id);
  return <h1>{product.name}</h1>;
}`,
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  {
    title: "What are the rendering strategies in Next.js (SSR, SSG, ISR, CSR)?",
    seoDescription: "SSG and ISR serve prerendered pages, SSR renders per request, CSR in the browser, PPR mixes them. First-byte timings from a Next.js 16.3.4 lab.",
    description: `**Question presented to candidate:**
"Walk me through SSG, ISR, SSR, CSR and PPR in Next.js. How do you get each one in the App Router, and how do you choose?"

**What a strong answer should cover:**
- SSG (static): rendered at build time and served as a file; the default for routes without request data.
- ISR: static plus regeneration after a lifetime (\`revalidate\`) or on demand (\`revalidatePath\`, \`revalidateTag\`).
- SSR (dynamic): rendered on each request, triggered by request-time APIs or uncached data; improved by streaming with Suspense.
- CSR: rendering and data fetching in the browser inside Client Components, for interactive or private parts.
- PPR (Next.js 16 with Cache Components): a static shell with dynamic holes streamed in the same response; the build shows each route mode with a symbol.

**Clarifying questions expected:**
- "Is the data the same for every user?" — static or ISR; otherwise dynamic or holes.
- "How fresh must it be?" — decides ISR lifetimes and on-demand revalidation.

**Code / implementation expected:** Yes — one route per strategy.`,
    answer: `**Target Audience:** Frontend engineers preparing for Next.js interviews — assumes basic React and App Router familiarity.
**Difficulty:** Medium

> **How to read this doc:** Each idea is explained in plain language first, then tagged with \`📌 Interview term:\`. Every behaviour claim was checked against the Next.js 16.3.4 docs shipped with the package and, in the **Verified** section, against real output from a build or a running server.

## 1. Why This Even Matters — A Story First

Think of four bakeries. One bakes all bread before opening (SSG). One bakes before opening and bakes a fresh batch whenever a shelf gets too old (ISR). One bakes each loaf when you order (SSR). One hands you dough and an oven to bake at home (CSR). The modern bakery does the first for the loaf and the third for your personal message on the cake, in the same order (PPR).

## 2. The Core Idea

📌 **Interview term: SSG** — static site generation: rendering a route at build time and serving the stored result.

📌 **Interview term: SSR** — server-side rendering on each request.

📌 **Interview term: CSR** — client-side rendering: the browser builds the UI and fetches data with JavaScript after load.

<svg class="iq-diagram" width="100%" viewBox="0 0 660 336" role="img" aria-label="How each strategy served the same 1.2 to 1.5 s of work (lab). SSG / ISR, PPR, SSR + streaming, SSR, blocking">
  <defs>
    <marker id="nx03m5ur-arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto">
      <path class="d-arrow" d="M0,0 L7,3 L0,6 Z"/>
    </marker>
  </defs>
  <text class="d-text" x="330" y="24" text-anchor="middle">How each strategy served the same 1.2 to 1.5 s of work (lab)</text>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.1s" dur="0.45s" fill="freeze"/>
    <rect class="d-box-accent" x="24" y="46" width="612" height="44" rx="10"/>
    <circle class="d-box-accent" cx="46" cy="68" r="12"/>
    <text class="d-text d-accent" x="46" y="73" text-anchor="middle">1</text>
    <text class="d-text d-accent" x="70" y="73">SSG / ISR</text>
    <text class="d-sub" x="262" y="72">first byte 12 to 22 ms, served from the stored page</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.5s" dur="0.45s" fill="freeze"/>
    <rect class="d-box-accent" x="24" y="102" width="612" height="44" rx="10"/>
    <circle class="d-box-accent" cx="46" cy="124" r="12"/>
    <text class="d-text d-accent" x="46" y="129" text-anchor="middle">2</text>
    <text class="d-text d-accent" x="70" y="129">PPR</text>
    <text class="d-sub" x="262" y="128">16 ms for the shell, per-user hole about 1.2 s later</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.9s" dur="0.45s" fill="freeze"/>
    <rect class="d-box" x="24" y="158" width="612" height="44" rx="10"/>
    <circle class="d-box-accent" cx="46" cy="180" r="12"/>
    <text class="d-text d-accent" x="46" y="185" text-anchor="middle">3</text>
    <text class="d-text" x="70" y="185">SSR + streaming</text>
    <text class="d-sub" x="262" y="184">24 ms for the fallback, content about 1.5 s later</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="1.3s" dur="0.45s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="214" width="612" height="44" rx="10"/>
    <circle class="d-box-accent" cx="46" cy="236" r="12"/>
    <text class="d-text d-accent" x="46" y="241" text-anchor="middle">4</text>
    <text class="d-text" x="70" y="241">SSR, blocking</text>
    <text class="d-sub" x="262" y="240">1546 ms before the first byte</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="1.7s" dur="0.6s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="274" width="612" height="44" rx="10"/>
    <text class="d-sub" x="330" y="301" text-anchor="middle">CSR sent only loading placeholders in the HTML; content came after JavaScript and a data request</text>
  </g>
</svg>

The strategies trade freshness against speed, and streaming and PPR remove most of the waiting that used to come with freshness.

## 3. How you get each in the App Router

| Strategy | How | Build symbol |
| :--- | :--- | :--- |
| SSG | No request data, cached or build-time fetches | ○ (or ● with generateStaticParams) |
| ISR | \`export const revalidate = n\`, fetch \`next.revalidate\`, or cacheLife | ○ with a revalidate time |
| SSR | cookies(), headers(), searchParams, connection(), no-store fetch | ƒ |
| Streaming SSR | loading.js or Suspense around slow parts | ƒ |
| PPR | \`cacheComponents: true\` plus Suspense holes | ◐ |
| CSR | Client Component fetching (SWR, TanStack Query) | depends on the page |

## 4. Choosing

Start static, add ISR when content changes, make only the per-request parts dynamic, and prefer holes (PPR or streaming) over whole-page dynamic rendering. Details: [static vs dynamic](/interview-question/what-is-the-difference-between-static-and-dynamic-rendering-in-the-next-js-app-r), [ISR](/interview-question/what-is-isr-incremental-static-regeneration-in-next-js-and-how-do-you-implement-), [PPR](/interview-question/what-is-partial-prerendering-ppr-in-next-js) and [choosing between them](/interview-question/ppr-vs-isr-vs-ssr-how-do-you-pick-the-rendering-strategy-in-next-15).

## 5. Verified — Timings for Each Strategy (Next.js 16.3.4, next start)

\`\`\`
each route requested twice (first request warms it), second one timed; page work = 1500 ms for the dynamic ones, 1200 ms for the PPR hole
static page (○)              first byte    12 ms   complete    13 ms   served from the prerendered file
ISR page (○ + 30s)           first byte    22 ms   complete    22 ms   prerendered, revalidated in the background
dynamic, no loading.js (ƒ)   first byte  1546 ms   complete  1548 ms   server waits 1500 ms before sending anything
dynamic + loading.js (ƒ)     first byte    24 ms   complete  1533 ms   fallback streams first, then the content
Partial Prerender (◐)        first byte    16 ms   complete  1233 ms   static shell + fallback first, hole streams in
\`\`\`

ISR regenerating in the background:

\`\`\`
GET /isr5 (export const revalidate = 5; the page prints its own render time)
t= 6.2s  request 1 (build copy expired) rendered=2026-09-23T06:00:04.222Z  x-nextjs-cache: STALE
t= 6.2s  request 2 (immediately after)  rendered=2026-09-23T06:00:04.222Z  x-nextjs-cache: STALE
t= 7.2s  request 3 (1 s later)          rendered=2026-09-23T06:00:40.971Z  x-nextjs-cache: HIT
t= 7.3s  request 4                      rendered=2026-09-23T06:00:40.971Z  x-nextjs-cache: HIT
t=13.3s  request 5 (6 s later: stale)   rendered=2026-09-23T06:00:40.971Z  x-nextjs-cache: STALE
t=14.1s  request 6                      rendered=2026-09-23T06:00:48.084Z  x-nextjs-cache: HIT
\`\`\`

CSR, as the first HTML shows it:

\`\`\`
/swr: a static page with three client components, each calling useSWR("/api/time", fetcher)
server HTML (what arrives before JavaScript): SWR-one loading|SWR-two loading|SWR-three loading|
browser, after hydration:     SWR-one 2026-09-23T06:00:55.890Z | SWR-two 2026-09-23T06:00:55.890Z | SWR-three 2026-09-23T06:00:55.890Z
requests to /api/time after load: 1   (three hooks, one shared key, one request)
after a window focus event:       2   (SWR revalidates on focus)
\`\`\`

## 6. Common Pitfalls

- **Making whole pages dynamic for one personal detail.** Use a Suspense hole or PPR.
- **CSR for SEO content.** The first HTML has only placeholders.
- **Expecting ISR to refresh on a timer.** It regenerates after a request arrives past the lifetime.
- **Reading cookies in a shared layout.** Every page below becomes dynamic.
- **Following Next.js 15 PPR instructions.** In 16 PPR comes with cacheComponents.

## 7. How to Answer in an Interview

<div style="background:#1c140a;border:2px solid #f9a825;border-radius:10px;padding:20px 24px;margin:20px 0;">

<div style="color:#ffca28;font-size:1.15em;font-weight:bold;margin-bottom:16px;">🎤 Quick Revision — read this the morning of the interview</div>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 10px 0;">The 60-Second Answer</div>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">1. The one-line answer:</strong> <span style="color:#f0e2c8;">SSG renders at build time, ISR adds regeneration, SSR renders per request, CSR renders in the browser, PPR mixes a static shell with dynamic holes.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">2. How it works:</strong> <span style="color:#f0e2c8;">In the App Router the mode follows from the code: request data makes a route dynamic, revalidate adds ISR, Suspense adds streaming.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">3. Why it matters:</strong> <span style="color:#f0e2c8;">In the lab stored pages answered in 12 to 22 ms and a blocking dynamic page took 1546 ms for its first byte.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">4. The detail to add:</strong> <span style="color:#f0e2c8;">Streaming and PPR sent the first byte in 16 to 24 ms while the per-request part followed.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">5. The trap to avoid:</strong> <span style="color:#f0e2c8;">Choose static first, add ISR, keep dynamic parts small, and use CSR only for interactive or private data.</span>
</blockquote>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:22px 0 10px 0;border-top:1px solid #4a3a1a;padding-top:16px;">Follow-Up Questions to Expect</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:12px 0 0 0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Which strategy is the default?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">Static: a route without request-time data is prerendered at build. With Cache Components, the default flips to dynamic and you opt parts into caching.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Is SSR in the App Router the same as getServerSideProps?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">The effect is the same (render per request), but it is triggered by what components read, not by a page function, and it can stream.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">How do you see which strategy a route got?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">The next build route table symbols (○, ●, ƒ, ◐) and the cache-control headers of responses.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">When is CSR still the right choice?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">For highly interactive or private screens, data that changes while the page is open, and anything that depends on browser-only state.</span>
</div>

</div>

## 8. Quick Glossary

| Term | Plain meaning |
| :--- | :--- |
| **SSG** | Rendered at build time |
| **ISR** | Static with regeneration |
| **SSR** | Rendered per request |
| **PPR** | Static shell plus streamed dynamic holes |

---
**Conclusion:** Next.js offers the whole range from build-time pages to per-request rendering, and in the App Router the choice follows from the code rather than from page functions. The lab put numbers on the range: milliseconds for stored pages, seconds for blocking dynamic ones, and streaming or PPR bridging the gap. Default to static and make only what must be dynamic dynamic.`,
    examples: [
      {
        label: "One route per strategy",
        tech: "tsx",
        runnable: false,
        code: `// SSG: app/about/page.tsx
export default function About() { return <h1>About us</h1>; }

// ISR: app/news/page.tsx
export const revalidate = 300;
export default async function News() { const n = await getNews(); return <List items={n} />; }

// SSR: app/account/page.tsx
import { cookies } from "next/headers";
export default async function Account() { const user = await getUser((await cookies()).get("sid")?.value); return <p>{user.name}</p>; }

// CSR: components/Live.tsx
"use client";
import useSWR from "swr";
export function Live() { const { data } = useSWR("/api/live", (u) => fetch(u).then((r) => r.json())); return <p>{data?.value ?? "..."}</p>; }

// PPR (next.config: cacheComponents: true): static shell + <Suspense><Personal /></Suspense>`,
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  {
    title: "What is the difference between Server Components and Client Components in Next.js?",
    seoDescription: "Server Components run only on the server and ship no code; Client Components are server-rendered, then hydrated. Checked on Next.js 16.3.4.",
    description: `**Question presented to candidate:**
"In the App Router, what is the difference between a Server Component and a Client Component, how do you decide which to use, and how do they work together?"

**What a strong answer should cover:**
- Server Components are the default in app/: they run only on the server, can be async, can read databases and secrets, and send no JavaScript to the browser.
- Client Components start at a \`'use client'\` file: they are server-rendered to HTML and then hydrated, so they can use state, effects, event handlers and browser APIs.
- A Client Component cannot import a Server Component, but can receive one as children or props.
- Props from server to client must be serializable (functions and class instances are rejected).
- Guideline: keep data and static UI on the server, push \`'use client'\` down to small interactive leaves.

**Clarifying questions expected:**
- "Which parts need interactivity or browser APIs?" — only those need to be Client Components.
- "Does anything touch secrets or the database?" — keep it on the server with server-only.

**Code / implementation expected:** Yes — a server page composing a client leaf.`,
    answer: `**Target Audience:** Frontend engineers preparing for Next.js interviews — assumes basic React and App Router familiarity.
**Difficulty:** Medium

> **How to read this doc:** Each idea is explained in plain language first, then tagged with \`📌 Interview term:\`. Every behaviour claim was checked against the Next.js 16.3.4 docs shipped with the package and, in the **Verified** section, against real output from a build or a running server.

## 1. Why This Even Matters — A Story First

A Server Component is a chef who prepares the dish in the kitchen and sends out the finished plate. A Client Component is a plate that comes with a burner, so the guest can keep it warm or flambé it at the table. Most dishes need no burner; you add one only where the guest must interact with the food.

## 2. The Core Idea

📌 **Interview term: Server Component** — a React component that renders only on the server; its code and dependencies never reach the browser.

📌 **Interview term: Client Component** — a component in the client module graph (from a 'use client' entry); it is server-rendered and then hydrated in the browser.

📌 **Interview term: Hydration** — attaching React state and event handlers to server-rendered HTML in the browser.

<svg class="iq-diagram" width="100%" viewBox="0 0 660 268" role="img" aria-label="Two kinds of components in one tree. Server Component, Client Component">
  <defs>
    <marker id="nx04q23u-arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto">
      <path class="d-arrow" d="M0,0 L7,3 L0,6 Z"/>
    </marker>
  </defs>
  <text class="d-text" x="330" y="24" text-anchor="middle">Two kinds of components in one tree</text>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.1s" dur="0.5s" fill="freeze"/>
    <rect class="d-box-accent" x="24" y="48" width="280" height="136" rx="10"/>
    <text class="d-text d-accent" x="164" y="78" text-anchor="middle">Server Component</text>
    <text class="d-sub" x="164" y="106" text-anchor="middle">runs only on the server</text>
    <text class="d-sub" x="164" y="128" text-anchor="middle">async, DB and secrets</text>
    <text class="d-sub" x="164" y="150" text-anchor="middle">ships no JavaScript</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.5s" dur="0.4s" fill="freeze"/>
    <path class="d-edge" d="M 307 116 L 353 116" marker-end="url(#nx04q23u-arrow)"/>
    <circle class="d-accent" r="5">
      <animateMotion dur="2s" repeatCount="indefinite" path="M 307 116 L 353 116"/>
      <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.12;0.88;1" dur="2s" repeatCount="indefinite"/>
    </circle>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="0.9s" dur="0.5s" fill="freeze"/>
    <rect class="d-box" x="356" y="48" width="280" height="136" rx="10"/>
    <text class="d-text" x="496" y="78" text-anchor="middle">Client Component</text>
    <text class="d-sub" x="496" y="106" text-anchor="middle">server-rendered, then hydrated</text>
    <text class="d-sub" x="496" y="128" text-anchor="middle">state, effects, events</text>
    <text class="d-sub" x="496" y="150" text-anchor="middle">code ships to the browser</text>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" begin="1.3s" dur="0.6s" fill="freeze"/>
    <rect class="d-box-muted" x="24" y="206" width="612" height="44" rx="10"/>
    <text class="d-sub" x="330" y="233" text-anchor="middle">lab: a server-only module was in 0 client files; the client Counter was in the first HTML</text>
  </g>
</svg>

The split is about where code runs, not about HTML: both kinds appear in the first HTML, but only Client Components continue to run in the browser.

## 3. Side by side

| | Server Component | Client Component |
| :--- | :--- | :--- |
| Default in app/ | Yes | No, needs 'use client' (or a client importer) |
| Runs | Server only | Server (SSR) and browser |
| async component | Yes | No |
| useState, useEffect, handlers | No | Yes |
| Access to DB, secrets, fs | Yes | No |
| JavaScript sent to the browser | None | Its code and imports |
| Can render the other kind | Yes, as children or imports | Only via children or props |

## 4. Composition

Pass Server Components into Client Components as \`children\`: the server renders them and the client receives only the result. Props must be serializable. More detail: ['use client'](/interview-question/what-is-the-use-client-directive-and-when-do-you-need-it), [React Server Components](/interview-question/what-are-react-server-components-and-why-does-next-js-use-them) and [passing data](/interview-question/how-do-you-pass-data-from-server-components-to-client-components-in-next-js).

## 5. Verified — What Each Kind Produced (Next.js 16.3.4)

Where code ended up after \`next build\`:

\`\`\`
count of build files that contain each marker string (client = .next/static, server = .next/server)
marker                                                        client  server
Inner.tsx                    1 client file(s),   2 server file(s)   <- NO directive, imported by a client component
ServerPart.tsx               0 client file(s),   5 server file(s)   <- NO directive, passed as children from a server page
heavy-server.ts              0 client file(s),   5 server file(s)   <- imported only by a server page
\`\`\`

What crossed the boundary and what did not:

\`\`\`
serial/date     -> type=[object Date] value=Thu Jan 01 1970 05:30:00 GMT+0530 (India Standard Time)
serial/map      -> type=[object Map] value=[object Map]
serial/set      -> type=[object Set] value=[object Set]
serial/bigint   -> type=[object BigInt] value=10
serial/promise  -> type=[object String] value=resolved on the server
serial/nested   -> type=[object Object] value=[object Object]
\`\`\`

Misuse caught by \`next dev\`:

\`\`\`
Error: 'server-only' cannot be imported from a Client Component module
Error: You're importing a module that depends on "server-only". This API is only available in Server Components in the App Router, but you are using it in the Pages Router.
Error: You're importing a module that depends on \`useState\` into a React Server Component module. This API is only available in Client Components. To fix, mark the file (or its parent) with the \`"use client"\` directive.
\`\`\`

## 6. Common Pitfalls

- **'use client' at the top of the tree.** Everything below becomes client code; keep it on leaves.
- **Hooks in a Server Component.** The build stops with a message to add 'use client'.
- **Importing a Server Component into a Client Component.** It becomes client code; pass it as children instead.
- **Non-serializable props.** Functions and class instances cannot cross; use Server Actions for callbacks.
- **Secrets in shared modules.** Guard server modules with import "server-only".

## 7. How to Answer in an Interview

<div style="background:#1c140a;border:2px solid #f9a825;border-radius:10px;padding:20px 24px;margin:20px 0;">

<div style="color:#ffca28;font-size:1.15em;font-weight:bold;margin-bottom:16px;">🎤 Quick Revision — read this the morning of the interview</div>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:0 0 10px 0;">The 60-Second Answer</div>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">1. The one-line answer:</strong> <span style="color:#f0e2c8;">Server Components are the default: they run only on the server, can be async and read data directly, and ship no JavaScript.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">2. How it works:</strong> <span style="color:#f0e2c8;">Client Components start at 'use client': they are server-rendered and hydrated, so they can use state, effects and events.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">3. Why it matters:</strong> <span style="color:#f0e2c8;">In the lab a server-only module appeared in 0 client files, while the client Counter still rendered into the first HTML.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">4. The detail to add:</strong> <span style="color:#f0e2c8;">They compose through children and props; props must be serializable, and a function prop was rejected.</span>
</blockquote>

<blockquote style="border-left:3px solid #f9a825;margin:10px 0;padding:2px 0 2px 14px;color:#f0e2c8;">
<strong style="color:#ffca28;">5. The trap to avoid:</strong> <span style="color:#f0e2c8;">Keep data and static UI on the server and put 'use client' on small interactive leaves.</span>
</blockquote>

<div style="color:#e0a83e;font-size:0.8em;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;margin:22px 0 10px 0;border-top:1px solid #4a3a1a;padding-top:16px;">Follow-Up Questions to Expect</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:12px 0 0 0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Are Client Components rendered on the server?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">Yes, for the first HTML; then they hydrate. The lab counter button was in the HTML with its initial value before any JavaScript.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Can a Server Component use context?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">No. Provide context from a Client Component provider placed in a layout; Server Components pass data as props instead.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">How do you call server code from a Client Component?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0 0 14px 0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">Through a Server Action (a 'use server' function) or a Route Handler.</span>
</div>

<div style="background:#3d2810;border-radius:8px 8px 0 0;padding:10px 16px;margin:0;">
<span style="color:#ff8a65;font-weight:bold;">❓ Q:</span> <span style="color:#ffe0b2;">Do Server Components re-render on the client?</span>
</div>
<div style="background:#151a15;border:1px solid #f9a825;border-top:none;border-radius:0 0 8px 8px;padding:10px 16px;margin:0;">
<span style="color:#66bb6a;font-weight:bold;">💡 A:</span> <span style="color:#d8d8d8;">No; to update them, navigate, call router.refresh(), or revalidate from a Server Action so the server sends a new payload.</span>
</div>

</div>

## 8. Quick Glossary

| Term | Plain meaning |
| :--- | :--- |
| **Server Component** | Server-only component, no client code |
| **Client Component** | Hydrated component from a 'use client' entry |
| **Hydration** | Attaching React to server HTML |
| **server-only** | Package that blocks client imports of a module |

---
**Conclusion:** Server Components and Client Components split the tree by where code runs: on the server only, or on the server and then in the browser. The lab showed server-only code staying out of client bundles, client components still rendering into HTML, and the serialization rules at the boundary. Default to the server and opt into the client where interaction needs it.`,
    examples: [
      {
        label: "A server page composing a small client leaf",
        tech: "tsx",
        runnable: false,
        code: `// app/products/page.tsx (Server Component)
import "server-only";
import { db } from "@/lib/db";
import AddToCart from "./AddToCart";

export default async function Products() {
  const products = await db.product.findMany();
  return (
    <ul>
      {products.map((p) => (
        <li key={p.id}>
          {p.name} <AddToCart productId={p.id} />
        </li>
      ))}
    </ul>
  );
}

// app/products/AddToCart.tsx (Client Component)
"use client";
import { useState } from "react";
import { addToCart } from "./actions"; // a Server Action
export default function AddToCart({ productId }: { productId: string }) {
  const [added, setAdded] = useState(false);
  return <button onClick={async () => { await addToCart(productId); setAdded(true); }}>{added ? "Added" : "Add"}</button>;
}`,
      },
    ],
  },
];

export default augments;
