/**
 * Node Phase N1 — merge duplicate-variant questions into one canonical each.
 * For every variant this:
 *   1. removes it from question-bank.json[nodejs] (its seed source),
 *   2. deletes the DB row (match {slug,title} so it's idempotent; comments cascade),
 *   3. records a redirect (variant slug → canonical slug).
 * Orphaned node-augments*.ts entries for deleted titles become harmless no-ops.
 *
 * Writes the redirect list to src/lib/node-merge-redirects.ts (spread into
 * next.config.ts). Idempotent.
 *
 *   npx tsx scripts/node-merge-duplicates.ts
 */
import { PrismaClient } from "@prisma/client";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const prisma = new PrismaClient();

// canonical title (kept) → variant titles (merged away + redirected)
const MERGES: Record<string, string[]> = {
  "How do you achieve concurrency in Node.js since it's single-threaded?": [
    "How does Node.js handle multi-threading behind the scenes if JavaScript is single-threaded?",
  ],
  "Explain how clustering works in Node.js.": [
    "What is the purpose of the cluster module and how does it utilize multi-core CPUs?",
  ],
  "Explain the differences between fork(), spawn(), and exec() in the child_process module.": [
    "What is the difference between spawn() and exec() in Node.js?",
  ],
  "Explain the purpose of `package.json` and `npm`.": [
    "What is `npm` and what are its core functionalities?",
  ],
  "What is the role of the path module and why is it preferred over manual string concatenation?": [
    "What is the difference between string concatenation and path.join/path.resolve?",
  ],
  "Describe the Node.js module system. What are CommonJS and ES Modules?": [
    "Explain the difference between require() and import in Node.js.",
  ],
  "How do you handle uncaught exceptions and unhandled promise rejections in Node.js?": [
    "What are 'unhandledRejections' and how do they differ from 'uncaughtExceptions'?",
  ],
};

const slugify = (s: string) =>
  s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 80) || "question";

async function main() {
  const variantTitles = Object.values(MERGES).flat();
  const dataDir = join(process.cwd(), "prisma", "data");

  // 1. validate canonicals exist
  for (const canon of Object.keys(MERGES)) {
    const c = await prisma.prepQuestion.findFirst({ where: { title: canon, technology: "nodejs" }, select: { id: true } });
    if (!c) console.log(`⚠ CANONICAL MISSING: ${canon}`);
  }

  // 2. remove variants from question-bank.json[nodejs]
  const qbPath = join(dataDir, "question-bank.json");
  const qbRaw = readFileSync(qbPath, "utf8");
  const qb = JSON.parse(qbRaw);
  const before = qb.nodejs.length;
  const removeSet = new Set(variantTitles);
  qb.nodejs = qb.nodejs.filter((q: any) => !removeSet.has(q.title));
  const indent = /\n( +)"/.exec(qbRaw)?.[1].length ?? 2;
  writeFileSync(qbPath, JSON.stringify(qb, null, indent));
  console.log(`question-bank.json[nodejs]: ${before} → ${qb.nodejs.length} (removed ${before - qb.nodejs.length})`);

  // 3. delete DB rows + collect redirects (slug computed deterministically so a
  //    redirect is recorded even if the row was already deleted in a prior run)
  const redirects: { from: string; to: string }[] = [];
  for (const [canon, variants] of Object.entries(MERGES)) {
    const canonSlug = slugify(canon);
    for (const v of variants) {
      const row = await prisma.prepQuestion.findFirst({
        where: { title: v, technology: "nodejs" },
        select: { id: true, slug: true, _count: { select: { comments: true } } },
      });
      const fromSlug = row?.slug ?? slugify(v);
      redirects.push({ from: `/interview-question/${fromSlug}`, to: `/interview-question/${canonSlug}` });
      if (!row) { console.log(`  (already merged) ${v}`); continue; }
      await prisma.prepQuestion.delete({ where: { id: row.id } });
      console.log(`  deleted ${row.slug} → ${canonSlug} (cascaded ${row._count.comments} comments)`);
    }
  }

  // 4. write redirect module (merge with any prior, dedup by `from`)
  const redirPath = join(process.cwd(), "src", "lib", "node-merge-redirects.ts");
  let existing: { from: string; to: string }[] = [];
  try {
    const prev = readFileSync(redirPath, "utf8");
    const m = prev.match(/\[([\s\S]*)\]/);
    if (m) existing = JSON.parse("[" + m[1].replace(/,\s*$/, "") + "]");
  } catch { /* first run */ }
  const byFrom = new Map(existing.map((r) => [r.from, r]));
  for (const r of redirects) byFrom.set(r.from, r);
  const all = [...byFrom.values()];
  const body =
    `// AUTO-GENERATED by scripts/node-merge-duplicates.ts — merged duplicate Node.js\n` +
    `// questions redirect to their canonical pages. Spread into next.config redirects().\n` +
    `export const nodeMergeRedirects = ${JSON.stringify(all, null, 2)}.map((r) => ({\n` +
    `  source: r.from,\n  destination: r.to,\n  permanent: true,\n}));\n`;
  writeFileSync(redirPath, body);
  console.log(`\nWrote ${all.length} redirects → src/lib/node-merge-redirects.ts`);

  await prisma.$disconnect();
}

main().catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
